#+TITLE: EG postupy: Co udělat při výměně údajů mezi agendami a informačními systémy
#+AUTHOR: Neoficiální metodický a kontrolní materiál od egdilna.cz v rámci typizovaných EG postupů pro úřady
#+LANGUAGE: cs
#+OPTIONS: H:4 toc:nil prop:1  
#+TODO: NEZAHÁJENO(n) ZADÁNO(z) ROZPRACOVANÉ(r) DODĚLAT(d) POKOREKTUŘE UPRAVOVÁNO(u) | KEKOREKTUŘE(k) HOTOVO(h) FINÁLNÍ(f) AKTUALIZOVÁNO(a@)
Verze 0.1

* NEZAHÁJENO Úvod a použití
Toto je kontrolní seznam a postup zejména využitelný pro architekty a odborníky pro ICT v úřadech. Udává podrobnosti a návody, jak postupovat v jednotlivé oblasti.

Tento postup se týká toho, když si dva úřady mají mezi svými informačními systémy standardním způsobem vyměňovat údaje.

Postup najdete vždy v rámci repozitáře [[https://gitlab.com/egdilna/eg-postupy][Konkrétní postupy EG pro úřady]] na GitLabu EGdílna či odkazem z webu [[http://www.egdilna.cz][egdilna.cz]]

Aktuální verze

- 

Pracovní verze:

- https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org

Pracovní úkoly a změnové požadavky k tomuto postupu najdete jako příslušné  issues v rámci [[https://gitlab.com/egdilna/eg-postupy/-/milestones/1][Milníku úkolů]]

* NEZAHÁJENO Rámec
S touto věcí souvisejí následující legislativní a architektonické oblasti a prvky. Využijte je také pro nastudování celého kontextu.
** NEZAHÁJENO Popis problematiky
** NEZAHÁJENO Legislativa
** NEZAHÁJENO Základní povinnosti
** NEZAHÁJENO Rámec IKČR
Z [[https://archi.gov.cz/ikcr][Informační koncepce ČR]] 
souvisejí následující

Související cíle (realizují se tím)

- Dílčí cíl 1.3: Rozvoj univerzálních front-office služeb
- Dílčí cíl 3.4: Zkvalitnění Registru práv a povinností a jeho obsahu
- Dílčí cíl 4.7: Zavedení procesního řízení a řízení služeb ve veřejné správě
- Dílčí cíl 5.6: Standardizace v EG a službách
- Dílčí cíl 5.9: Rozvoj Propojeného datového fondu (PPDF)

Související architektonické principy a zásady  (je v souladu)

- Architektonický princip P02: Zásada „pouze jednou“
- Architektonický princip P08: Jeden stát
- Architektonický princip P09: Sdílené služby veřejné správy
- Architektonický princip P16: Konsolidace a propojování informačních systémů veřejné správy
- Zásada řízení ICT Z01: Na prvním místě je klient
- Zásada řízení ICT Z05: Řízení požadavků a změn
- Zásada řízení ICT Z09: Udržení interních kompetencí
- Zásada řízení ICT Z10: Procesní řízení
- Zásada řízení ICT Z11: Řízení přínosů a hodnoty

** NEZAHÁJENO Národní architektura
* NEZAHÁJENO Strany a jejich role
* NEZAHÁJENO Seznam co udělat
Na tyto věci je třeba si dávat pozor a při jednáních je uplatňovat a společně je řešit. Lze využít také jako jednoduchý návod a krokový seznam při přípravě, projednávání a realizaci souvisejících projektů.
    #+TITLE: EG postupy: Co udělat při výměně údajů mezi agendami a informačními systémy
#+AUTHOR: Neoficiální metodický a kontrolní materiál od egdilna.cz v rámci typizovaných EG postupů pro úřady
#+LANGUAGE: cs
#+OPTIONS: H:4 toc:nil prop:1  
#+TODO: NEZAHÁJENO(n) ZADÁNO(z) ROZPRACOVANÉ(r) DODĚLAT(d) POKOREKTUŘE UPRAVOVÁNO(u) | KEKOREKTUŘE(k) HOTOVO(h) FINÁLNÍ(f) AKTUALIZOVÁNO(a@)
Verze 0.1

* NEZAHÁJENO Úvod a použití
Toto je kontrolní seznam a postup zejména využitelný pro architekty a odborníky pro ICT v úřadech. Udává podrobnosti a návody, jak postupovat v jednotlivé oblasti.

Tento postup se týká toho, když si dva úřady mají mezi svými informačními systémy standardním způsobem vyměňovat údaje.

Postup najdete vždy v rámci repozitáře [[https://gitlab.com/egdilna/eg-postupy][Konkrétní postupy EG pro úřady]] na GitLabu EGdílna či odkazem z webu [[http://www.egdilna.cz][egdilna.cz]]

Aktuální verze

- 

Pracovní verze:

- [[https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org][https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org]]

Pracovní úkoly a změnové požadavky k tomuto postupu najdete jako příslušné  issues v rámci [[https://gitlab.com/egdilna/eg-postupy/-/milestones/1][Milníku úkolů]]

* NEZAHÁJENO Rámec
S touto věcí souvisejí následující legislativní a architektonické oblasti a prvky. Využijte je také pro nastudování celého kontextu.
** NEZAHÁJENO Popis problematiky
** NEZAHÁJENO Legislativa
** NEZAHÁJENO Základní povinnosti
** NEZAHÁJENO Rámec IKČR
Související cíle (realizují se tím)

- Dílčí cíl 1.3: Rozvoj univerzálních front-office služeb
- Dílčí cíl 3.4: Zkvalitnění Registru práv a povinností a jeho obsahu
- Dílčí cíl 4.7: Zavedení procesního řízení a řízení služeb ve veřejné správě
- Dílčí cíl 5.6: Standardizace v EG a službách
- Dílčí cíl 5.9: Rozvoj Propojeného datového fondu (PPDF)

Z [[https://archi.gov.cz/ikcr][Informační koncepce ČR]] souvisejí následující

Související architektonické principy a zásady  (je v souladu)

- Architektonický princip P02: Zásada „pouze jednou“
- Architektonický princip P08: Jeden stát
- Architektonický princip P09: Sdílené služby veřejné správy
- Architektonický princip P16: Konsolidace a propojování informačních systémů veřejné správy
- Zásada řízení ICT Z01: Na prvním místě je klient
- Zásada řízení ICT Z05: Řízení požadavků a změn
- Zásada řízení ICT Z09: Udržení interních kompetencí
- Zásada řízení ICT Z10: Procesní řízení
- Zásada řízení ICT Z11: Řízení přínosů a hodnoty

** NEZAHÁJENO Národní architektura
* NEZAHÁJENO Strany a jejich role
* NEZAHÁJENO Seznam co udělat
Na tyto věci je třeba si dávat pozor a při jednáních je uplatňovat a společně je řešit. Lze využít také jako jednoduchý návod a krokový seznam při přípravě, projednávání a realizaci souvisejících projektů.
    #+TITLE: EG postupy: Co udělat při výměně údajů mezi agendami a informačními systémy
#+AUTHOR: Neoficiální metodický a kontrolní materiál od egdilna.cz v rámci typizovaných EG postupů pro úřady
#+LANGUAGE: cs
#+OPTIONS: H:4 toc:nil prop:1  
#+TODO: NEZAHÁJENO(n) ZADÁNO(z) ROZPRACOVANÉ(r) DODĚLAT(d) POKOREKTUŘE UPRAVOVÁNO(u) | KEKOREKTUŘE(k) HOTOVO(h) FINÁLNÍ(f) AKTUALIZOVÁNO(a@)
Verze 0.1

* NEZAHÁJENO Úvod a použití
Toto je kontrolní seznam a postup zejména využitelný pro architekty a odborníky pro ICT v úřadech. Udává podrobnosti a návody, jak postupovat v jednotlivé oblasti.

Tento postup se týká toho, když si dva úřady mají mezi svými informačními systémy standardním způsobem vyměňovat údaje.

Postup najdete vždy v rámci repozitáře [[https://gitlab.com/egdilna/eg-postupy][Konkrétní postupy EG pro úřady]] na GitLabu EGdílna či odkazem z webu [[http://www.egdilna.cz][egdilna.cz]]

Aktuální verze

- 

Pracovní verze:

- https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org

Pracovní úkoly a změnové požadavky k tomuto postupu najdete jako příslušné  issues v rámci [[https://gitlab.com/egdilna/eg-postupy/-/milestones/1][Milníku úkolů]]

* NEZAHÁJENO Rámec
S touto věcí souvisejí následující legislativní a architektonické oblasti a prvky. Využijte je také pro nastudování celého kontextu.
** NEZAHÁJENO Popis problematiky
** NEZAHÁJENO Legislativa
** NEZAHÁJENO Základní povinnosti
** NEZAHÁJENO Rámec IKČR

Z [[https://archi.gov.cz/ikcr][Informační koncepce ČR]] 
souvisejí následující

-----

Související cíle (realizují se tím)

- Dílčí cíl 1.3: Rozvoj univerzálních front-office služeb
- Dílčí cíl 3.4: Zkvalitnění Registru práv a povinností a jeho obsahu
- Dílčí cíl 4.7: Zavedení procesního řízení a řízení služeb ve veřejné správě
- Dílčí cíl 5.6: Standardizace v EG a službách
- Dílčí cíl 5.9: Rozvoj Propojeného datového fondu (PPDF)

-----

Související architektonické principy a zásady  (je v souladu)

- Architektonický princip P02: Zásada „pouze jednou“
- Architektonický princip P08: Jeden stát
- Architektonický princip P09: Sdílené služby veřejné správy
- Architektonický princip P16: Konsolidace a propojování informačních systémů veřejné správy
- Zásada řízení ICT Z01: Na prvním místě je klient
- Zásada řízení ICT Z05: Řízení požadavků a změn
- Zásada řízení ICT Z09: Udržení interních kompetencí
- Zásada řízení ICT Z10: Procesní řízení
- Zásada řízení ICT Z11: Řízení přínosů a hodnoty

** NEZAHÁJENO Národní architektura
* NEZAHÁJENO Strany a jejich role
* NEZAHÁJENO Seznam co udělat
Na tyto věci je třeba si dávat pozor a při jednáních je uplatňovat a společně je řešit. Lze využít také jako jednoduchý návod a krokový seznam při přípravě, projednávání a realizaci souvisejících projektů.
    #+TITLE: EG postupy: Co udělat při výměně údajů mezi agendami a informačními systémy
#+AUTHOR: Neoficiální metodický a kontrolní materiál od egdilna.cz v rámci typizovaných EG postupů pro úřady
#+LANGUAGE: cs
#+OPTIONS: H:4 toc:nil prop:1  
#+TODO: NEZAHÁJENO(n) ZADÁNO(z) ROZPRACOVANÉ(r) DODĚLAT(d) POKOREKTUŘE UPRAVOVÁNO(u) | KEKOREKTUŘE(k) HOTOVO(h) FINÁLNÍ(f) AKTUALIZOVÁNO(a@)
Verze 0.1

* NEZAHÁJENO Úvod a použití
Toto je kontrolní seznam a postup zejména využitelný pro architekty a odborníky pro ICT v úřadech. Udává podrobnosti a návody, jak postupovat v jednotlivé oblasti.

Tento postup se týká toho, když si dva úřady mají mezi svými informačními systémy standardním způsobem vyměňovat údaje.

Postup najdete vždy v rámci repozitáře [[https://gitlab.com/egdilna/eg-postupy][Konkrétní postupy EG pro úřady]] na GitLabu EGdílna či odkazem z webu [[http://www.egdilna.cz][egdilna.cz]]

Aktuální verze

- 

Pracovní verze:

- [[https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org][https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org]]

Pracovní úkoly a změnové požadavky k tomuto postupu najdete jako příslušné  issues v rámci [[https://gitlab.com/egdilna/eg-postupy/-/milestones/1][Milníku úkolů]]

* NEZAHÁJENO Rámec
S touto věcí souvisejí následující legislativní a architektonické oblasti a prvky. Využijte je také pro nastudování celého kontextu.
** NEZAHÁJENO Popis problematiky
** NEZAHÁJENO Legislativa
** NEZAHÁJENO Základní povinnosti
** NEZAHÁJENO Rámec IKČR
Související cíle (realizují se tím)

- Dílčí cíl 1.3: Rozvoj univerzálních front-office služeb
- Dílčí cíl 3.4: Zkvalitnění Registru práv a povinností a jeho obsahu
- Dílčí cíl 4.7: Zavedení procesního řízení a řízení služeb ve veřejné správě
- Dílčí cíl 5.6: Standardizace v EG a službách
- Dílčí cíl 5.9: Rozvoj Propojeného datového fondu (PPDF)

Z [[https://archi.gov.cz/ikcr][Informační koncepce ČR]] souvisejí následující

Související architektonické principy a zásady  (je v souladu)

- Architektonický princip P02: Zásada „pouze jednou“
- Architektonický princip P08: Jeden stát
- Architektonický princip P09: Sdílené služby veřejné správy
- Architektonický princip P16: Konsolidace a propojování informačních systémů veřejné správy
- Zásada řízení ICT Z01: Na prvním místě je klient
- Zásada řízení ICT Z05: Řízení požadavků a změn
- Zásada řízení ICT Z09: Udržení interních kompetencí
- Zásada řízení ICT Z10: Procesní řízení
- Zásada řízení ICT Z11: Řízení přínosů a hodnoty

** NEZAHÁJENO Národní architektura
* NEZAHÁJENO Strany a jejich role
* NEZAHÁJENO Seznam co udělat
Na tyto věci je třeba si dávat pozor a při jednáních je uplatňovat a společně je řešit. Lze využít také jako jednoduchý návod a krokový seznam při přípravě, projednávání a realizaci souvisejících projektů.
    #+TITLE: EG postupy: Co udělat při výměně údajů mezi agendami a informačními systémy
#+AUTHOR: Neoficiální metodický a kontrolní materiál od egdilna.cz v rámci typizovaných EG postupů pro úřady
#+LANGUAGE: cs
#+OPTIONS: H:4 toc:nil prop:1  
#+TODO: NEZAHÁJENO(n) ZADÁNO(z) ROZPRACOVANÉ(r) DODĚLAT(d) POKOREKTUŘE UPRAVOVÁNO(u) | KEKOREKTUŘE(k) HOTOVO(h) FINÁLNÍ(f) AKTUALIZOVÁNO(a@)
Verze 0.1

* NEZAHÁJENO Úvod a použití
Toto je kontrolní seznam a postup zejména využitelný pro architekty a odborníky pro ICT v úřadech. Udává podrobnosti a návody, jak postupovat v jednotlivé oblasti.

Tento postup se týká toho, když si dva úřady mají mezi svými informačními systémy standardním způsobem vyměňovat údaje.

Postup najdete vždy v rámci repozitáře [[https://gitlab.com/egdilna/eg-postupy][Konkrétní postupy EG pro úřady]] na GitLabu EGdílna či odkazem z webu [[http://www.egdilna.cz][egdilna.cz]]

Aktuální verze

- 

Pracovní verze:

- https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org

Pracovní úkoly a změnové požadavky k tomuto postupu najdete jako příslušné  issues v rámci [[https://gitlab.com/egdilna/eg-postupy/-/milestones/1][Milníku úkolů]]

* NEZAHÁJENO Rámec
S touto věcí souvisejí následující legislativní a architektonické oblasti a prvky. Využijte je také pro nastudování celého kontextu.
** NEZAHÁJENO Popis problematiky
** NEZAHÁJENO Legislativa
** NEZAHÁJENO Základní povinnosti
** NEZAHÁJENO Rámec IKČR
Z [[https://archi.gov.cz/ikcr][Informační koncepce ČR]] 
souvisejí následující

Související cíle (realizují se tím)

- Dílčí cíl 1.3: Rozvoj univerzálních front-office služeb
- Dílčí cíl 3.4: Zkvalitnění Registru práv a povinností a jeho obsahu
- Dílčí cíl 4.7: Zavedení procesního řízení a řízení služeb ve veřejné správě
- Dílčí cíl 5.6: Standardizace v EG a službách
- Dílčí cíl 5.9: Rozvoj Propojeného datového fondu (PPDF)

Související architektonické principy a zásady  (je v souladu)

- Architektonický princip P02: Zásada „pouze jednou“
- Architektonický princip P08: Jeden stát
- Architektonický princip P09: Sdílené služby veřejné správy
- Architektonický princip P16: Konsolidace a propojování informačních systémů veřejné správy
- Zásada řízení ICT Z01: Na prvním místě je klient
- Zásada řízení ICT Z05: Řízení požadavků a změn
- Zásada řízení ICT Z09: Udržení interních kompetencí
- Zásada řízení ICT Z10: Procesní řízení
- Zásada řízení ICT Z11: Řízení přínosů a hodnoty

** NEZAHÁJENO Národní architektura
* NEZAHÁJENO Strany a jejich role
* NEZAHÁJENO Seznam co udělat
Na tyto věci je třeba si dávat pozor a při jednáních je uplatňovat a společně je řešit. Lze využít také jako jednoduchý návod a krokový seznam při přípravě, projednávání a realizaci souvisejících projektů.
    #+TITLE: EG postupy: Co udělat při výměně údajů mezi agendami a informačními systémy
#+AUTHOR: Neoficiální metodický a kontrolní materiál od egdilna.cz v rámci typizovaných EG postupů pro úřady
#+LANGUAGE: cs
#+OPTIONS: H:4 toc:nil prop:1  
#+TODO: NEZAHÁJENO(n) ZADÁNO(z) ROZPRACOVANÉ(r) DODĚLAT(d) POKOREKTUŘE UPRAVOVÁNO(u) | KEKOREKTUŘE(k) HOTOVO(h) FINÁLNÍ(f) AKTUALIZOVÁNO(a@)
Verze 0.1

* NEZAHÁJENO Úvod a použití
Toto je kontrolní seznam a postup zejména využitelný pro architekty a odborníky pro ICT v úřadech. Udává podrobnosti a návody, jak postupovat v jednotlivé oblasti.

Tento postup se týká toho, když si dva úřady mají mezi svými informačními systémy standardním způsobem vyměňovat údaje.

Postup najdete vždy v rámci repozitáře [[https://gitlab.com/egdilna/eg-postupy][Konkrétní postupy EG pro úřady]] na GitLabu EGdílna či odkazem z webu [[http://www.egdilna.cz][egdilna.cz]]

Aktuální verze

- 

Pracovní verze:

- [[https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org][https://gitlab.com/egdilna/eg-postupy/-/blob/Work/Kontroln%C3%AD%20seznam%20Co%20udělat%20při%20výměně%20údajů.org]]

Pracovní úkoly a změnové požadavky k tomuto postupu najdete jako příslušné  issues v rámci [[https://gitlab.com/egdilna/eg-postupy/-/milestones/1][Milníku úkolů]]

* NEZAHÁJENO Rámec
S touto věcí souvisejí následující legislativní a architektonické oblasti a prvky. Využijte je také pro nastudování celého kontextu.
** NEZAHÁJENO Popis problematiky
** NEZAHÁJENO Legislativa
** NEZAHÁJENO Základní povinnosti
** NEZAHÁJENO Rámec IKČR
Související cíle (realizují se tím)

- Dílčí cíl 1.3: Rozvoj univerzálních front-office služeb
- Dílčí cíl 3.4: Zkvalitnění Registru práv a povinností a jeho obsahu
- Dílčí cíl 4.7: Zavedení procesního řízení a řízení služeb ve veřejné správě
- Dílčí cíl 5.6: Standardizace v EG a službách
- Dílčí cíl 5.9: Rozvoj Propojeného datového fondu (PPDF)

Z [[https://archi.gov.cz/ikcr][Informační koncepce ČR]] souvisejí následující

Související architektonické principy a zásady  (je v souladu)

- Architektonický princip P02: Zásada „pouze jednou“
- Architektonický princip P08: Jeden stát
- Architektonický princip P09: Sdílené služby veřejné správy
- Architektonický princip P16: Konsolidace a propojování informačních systémů veřejné správy
- Zásada řízení ICT Z01: Na prvním místě je klient
- Zásada řízení ICT Z05: Řízení požadavků a změn
- Zásada řízení ICT Z09: Udržení interních kompetencí
- Zásada řízení ICT Z10: Procesní řízení
- Zásada řízení ICT Z11: Řízení přínosů a hodnoty

** NEZAHÁJENO Národní architektura
* NEZAHÁJENO Strany a jejich role
* NEZAHÁJENO Seznam co udělat
Na tyto věci je třeba si dávat pozor a při jednáních je uplatňovat a společně je řešit. Lze využít také jako jednoduchý návod a krokový seznam při přípravě, projednávání a realizaci souvisejících projektů.
